image: node:16

.env: &env
  - echo "NX_GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY" > .env

.pre_deploy: &pre_deploy
  - yarn global add firebase-tools
  - yarn install
  - yarn build
  - firebase use $FIREBASE_PROJECT_ID --token $FIREBASE_TOKEN

cache:
  paths:
    - node_modules/

stages:
  - test
  - deploy

test:
  stage: test
  before_script:
    - yarn install
  allow_failure: false
  script:
    - yarn test:all --updateSnapshot

production:
  stage: deploy
  before_script:
    - *env
    - *pre_deploy
  only:
    - main
  allow_failure: false
  script:
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN --only hosting
